name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
          components: rustfmt, clippy

      - name: Ensure Rust is globally available
        run: rustup default stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --all --verbose

      - name: Run tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          export HOME="${{ runner.temp }}/fakehome"
          mkdir -p "$HOME"
          cargo test --all --verbose -- --test-threads=1

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:USERPROFILE = "${{ runner.temp }}\fakehome"
          New-Item -ItemType Directory -Force -Path "$env:USERPROFILE" | Out-Null
          cargo test --all --verbose -- --test-threads=1


  coverage:
    name: Coverage (Linux only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tests with coverage
        run: |
          export HOME="${{ runner.temp }}/fakehome"
          mkdir -p "$HOME"
          cargo test --all --verbose -- --test-threads=1

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tarpaulin-report/
